/var/spool/slurmd/job1231878/slurm_script: line 11: cd: /pubhome/xtzhang/myesm/: No such file or directory
/lustre/gst/xuchunfu/zhangxt/anaconda3/envs/protein_predict/lib/python3.8/site-packages/torch/distributed/launch.py:180: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torchrun.
Note that --use_env is set by default in torchrun.
If your script expects `--local_rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See 
https://pytorch.org/docs/stable/distributed.html#launch-utility for 
further instructions

  warnings.warn(
WARNING:torch.distributed.run:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
Traceback (most recent call last):
Traceback (most recent call last):
  File "/lustre/gst/xuchunfu/zhangxt/myesm/fie2_loss2.py", line 403, in <module>
Traceback (most recent call last):
  File "/lustre/gst/xuchunfu/zhangxt/myesm/fie2_loss2.py", line 403, in <module>
Traceback (most recent call last):
  File "/lustre/gst/xuchunfu/zhangxt/myesm/fie2_loss2.py", line 403, in <module>
  File "/lustre/gst/xuchunfu/zhangxt/myesm/fie2_loss2.py", line 403, in <module>
    ddp_main(args)
  File "/lustre/gst/xuchunfu/zhangxt/myesm/fie2_loss2.py", line 121, in ddp_main
    ddp_main(args)
  File "/lustre/gst/xuchunfu/zhangxt/myesm/fie2_loss2.py", line 121, in ddp_main
    ddp_main(args)
      File "/lustre/gst/xuchunfu/zhangxt/myesm/fie2_loss2.py", line 121, in ddp_main
run(args, train_set0, validation_set0, test_set0)
  File "/lustre/gst/xuchunfu/zhangxt/myesm/fie2_loss2.py", line 152, in run
    run(args, train_set0, validation_set0, test_set0)
  File "/lustre/gst/xuchunfu/zhangxt/myesm/fie2_loss2.py", line 152, in run
    ddp_main(args)        
run(args, train_set0, validation_set0, test_set0)model = load_model(  File "/lustre/gst/xuchunfu/zhangxt/myesm/fie2_loss2.py", line 121, in ddp_main


  File "/lustre/gst/xuchunfu/zhangxt/myesm/fie2_loss2.py", line 152, in run
  File "/lustre/gst/xuchunfu/zhangxt/myesm/TPFold.py", line 493, in load_model
    model = load_model(
  File "/lustre/gst/xuchunfu/zhangxt/myesm/TPFold.py", line 493, in load_model
    run(args, train_set0, validation_set0, test_set0)
  File "/lustre/gst/xuchunfu/zhangxt/myesm/fie2_loss2.py", line 152, in run
    model = load_model(
  File "/lustre/gst/xuchunfu/zhangxt/myesm/TPFold.py", line 493, in load_model
    model = load_model(
  File "/lustre/gst/xuchunfu/zhangxt/myesm/TPFold.py", line 493, in load_model
            model = ESMFold(pattern=pattern, num_tags=num_tags, add_tmbed=add_tmbed, esmfold_config=cfg) # make an instancemodel = ESMFold(pattern=pattern, num_tags=num_tags, add_tmbed=add_tmbed, esmfold_config=cfg) # make an instancemodel = ESMFold(pattern=pattern, num_tags=num_tags, add_tmbed=add_tmbed, esmfold_config=cfg) # make an instance


  File "/lustre/gst/xuchunfu/zhangxt/myesm/TPFold.py", line 74, in __init__
  File "/lustre/gst/xuchunfu/zhangxt/myesm/TPFold.py", line 74, in __init__
  File "/lustre/gst/xuchunfu/zhangxt/myesm/TPFold.py", line 74, in __init__
    model = ESMFold(pattern=pattern, num_tags=num_tags, add_tmbed=add_tmbed, esmfold_config=cfg) # make an instance
  File "/lustre/gst/xuchunfu/zhangxt/myesm/TPFold.py", line 74, in __init__
    self.esm, self.esm_dict = load_plm(esm2_path=self.cfg["plm_path"]["esm2_path"], ft_path=self.cfg["plm_path"]["ft_path"])
  File "/lustre/gst/xuchunfu/zhangxt/myesm/TPFold.py", line 32, in load_plm
        self.esm, self.esm_dict = load_plm(esm2_path=self.cfg["plm_path"]["esm2_path"], ft_path=self.cfg["plm_path"]["ft_path"])self.esm, self.esm_dict = load_plm(esm2_path=self.cfg["plm_path"]["esm2_path"], ft_path=self.cfg["plm_path"]["ft_path"])

      File "/lustre/gst/xuchunfu/zhangxt/myesm/TPFold.py", line 32, in load_plm
  File "/lustre/gst/xuchunfu/zhangxt/myesm/TPFold.py", line 32, in load_plm
ft_model_state = update_data['model_state_dict']
KeyError:     'model_state_dict'self.esm, self.esm_dict = load_plm(esm2_path=self.cfg["plm_path"]["esm2_path"], ft_path=self.cfg["plm_path"]["ft_path"])

  File "/lustre/gst/xuchunfu/zhangxt/myesm/TPFold.py", line 32, in load_plm
        ft_model_state = update_data['model_state_dict']ft_model_state = update_data['model_state_dict']

KeyErrorKeyError: : 'model_state_dict''model_state_dict'

    ft_model_state = update_data['model_state_dict']
KeyError: 'model_state_dict'
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 1593836) of binary: /lustre/gst/xuchunfu/zhangxt/anaconda3/envs/protein_predict/bin/python3
Traceback (most recent call last):
  File "/lustre/gst/xuchunfu/zhangxt/anaconda3/envs/protein_predict/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/lustre/gst/xuchunfu/zhangxt/anaconda3/envs/protein_predict/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/lustre/gst/xuchunfu/zhangxt/anaconda3/envs/protein_predict/lib/python3.8/site-packages/torch/distributed/launch.py", line 195, in <module>
    main()
  File "/lustre/gst/xuchunfu/zhangxt/anaconda3/envs/protein_predict/lib/python3.8/site-packages/torch/distributed/launch.py", line 191, in main
    launch(args)
  File "/lustre/gst/xuchunfu/zhangxt/anaconda3/envs/protein_predict/lib/python3.8/site-packages/torch/distributed/launch.py", line 176, in launch
    run(args)
  File "/lustre/gst/xuchunfu/zhangxt/anaconda3/envs/protein_predict/lib/python3.8/site-packages/torch/distributed/run.py", line 753, in run
    elastic_launch(
  File "/lustre/gst/xuchunfu/zhangxt/anaconda3/envs/protein_predict/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 132, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/lustre/gst/xuchunfu/zhangxt/anaconda3/envs/protein_predict/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 246, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
/lustre/gst/xuchunfu/zhangxt/myesm/fie2_loss2.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2023-05-16_04:43:06
  host      : c02b22n01
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 1593837)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[2]:
  time      : 2023-05-16_04:43:06
  host      : c02b22n01
  rank      : 2 (local_rank: 2)
  exitcode  : 1 (pid: 1593838)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[3]:
  time      : 2023-05-16_04:43:06
  host      : c02b22n01
  rank      : 3 (local_rank: 3)
  exitcode  : 1 (pid: 1593839)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-05-16_04:43:06
  host      : c02b22n01
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 1593836)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
